# Generated by Django 5.1 on 2024-09-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='data published')),
                ('pcv_index', models.FloatField(default=0)),
                ('total_area', models.FloatField(default=0)),
                ('total_green_area', models.FloatField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=30)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_area.neighborhood')),
            ],
        ),
    ]
