services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment: 
      - POSTGRES_USER=green-area
      - POSTGRES_PASSWORD=green-area
      - POSTGRES_DB=green-area
    volumes:
      - green_area_database:/bitnami/postgresql

volumes:
    green_area_database: